import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

part 'currency.freezed.dart';

@freezed
class Currency with _$Currency {
  factory Currency({
    required String code,
    required String name,
    required String pluralName,
    required String symbol,
    required String flag,
  }) = _Currency;

  factory Currency.fromCode(String code) {
    return currencies.firstWhere((element) => element.code == code);
  }
}

List<Currency> currencies = [
  Currency(
    name: 'United States Dollar',
    code: 'USD',
    pluralName: 'US dollars',
    symbol: '\$',
    flag: 'USD',
  ),
  Currency(
    name: 'Euro',
    code: 'EUR',
    pluralName: 'Euros',
    symbol: '€',
    flag: 'EUR',
  ),
  Currency(
    name: 'Japanese Yen',
    code: 'JPY',
    pluralName: 'Japanese yen',
    symbol: '¥',
    flag: 'JPY',
  ),
  Currency(
    name: 'British Pound',
    code: 'GBP',
    pluralName: 'British pounds sterling',
    symbol: '£',
    flag: 'GBP',
  ),
  Currency(
    name: 'Australian Dollar',
    code: 'AUD',
    pluralName: 'Australian dollars',
    symbol: '\$',
    flag: 'AUD',
  ),
  Currency(
    name: 'Canadian Dollar',
    code: 'CAD',
    pluralName: 'Canadian dollars',
    symbol: '\$',
    flag: 'CAD',
  ),
  Currency(
    name: 'Switzerland Franc',
    code: 'CHF',
    pluralName: 'Swiss francs',
    symbol: 'CHF',
    flag: 'CHF',
  ),
  Currency(
    name: 'Nepal Rupee',
    code: 'NPR',
    pluralName: 'Nepalese rupees',
    symbol: '₨',
    flag: 'NPR',
  ),
  Currency(
    name: 'China Yuan Renminbi',
    code: 'CNY',
    pluralName: 'Chinese yuan',
    symbol: '¥',
    flag: 'CNY',
  ),
  Currency(
    name: 'Hong Kong Dollar',
    code: 'HKD',
    pluralName: 'Hong Kong dollars',
    symbol: '\$',
    flag: 'HKD',
  ),
  Currency(
    name: 'New Zealand Dollar',
    code: 'NZD',
    pluralName: 'New Zealand dollars',
    symbol: '\$',
    flag: 'NZD',
  ),
  Currency(
    name: 'Sweden Krona',
    code: 'SEK',
    pluralName: 'Swedish kronor',
    symbol: 'kr',
    flag: 'SEK',
  ),
  Currency(
    name: 'Korea (South) Won',
    code: 'KRW',
    pluralName: 'South Korean won',
    symbol: '₩',
    flag: 'KRW',
  ),
  Currency(
    name: 'Singapore Dollar',
    code: 'SGD',
    pluralName: 'Singapore dollars',
    symbol: '\$',
    flag: 'SGD',
  ),
  Currency(
    name: 'Norway Krone',
    code: 'NOK',
    pluralName: 'Norwegian kroner',
    symbol: 'kr',
    flag: 'NOK',
  ),
  Currency(
    name: 'Mexico Peso',
    code: 'MXN',
    pluralName: 'Mexican pesos',
    symbol: '\$',
    flag: 'MXN',
  ),
  Currency(
    name: 'Indian Rupee',
    code: 'INR',
    pluralName: 'Indian rupees',
    symbol: '₹',
    flag: 'INR',
  ),
  Currency(
    name: 'Russia Ruble',
    code: 'RUB',
    pluralName: 'Russian rubles',
    symbol: '₽',
    flag: 'RUB',
  ),
  Currency(
    name: 'South Africa Rand',
    code: 'ZAR',
    pluralName: 'South African rand',
    symbol: 'R',
    flag: 'ZAR',
  ),
  Currency(
    name: 'Turkish Lira',
    code: 'TRY',
    pluralName: 'Turkish Lira',
    symbol: '₺',
    flag: 'TRY',
  ),
  Currency(
    name: 'Brazil Real',
    code: 'BRL',
    pluralName: 'Brazilian reals',
    symbol: 'R\$',
    flag: 'BRL',
  ),
  Currency(
    name: 'Taiwan New Dollar',
    code: 'TWD',
    pluralName: 'New Taiwan dollars',
    symbol: 'NT\$',
    flag: 'TWD',
  ),
  Currency(
    name: 'Denmark Krone',
    code: 'DKK',
    pluralName: 'Danish kroner',
    symbol: 'kr',
    flag: 'DKK',
  ),
  Currency(
    name: 'Poland Zloty',
    code: 'PLN',
    pluralName: 'Polish zlotys',
    symbol: 'zł',
    flag: 'PLN',
  ),
  Currency(
    name: 'Thailand Baht',
    code: 'THB',
    pluralName: 'Thai baht',
    symbol: '฿',
    flag: 'THB',
  ),
  Currency(
    name: 'Indonesia Rupiah',
    code: 'IDR',
    pluralName: 'Indonesian rupiahs',
    symbol: 'Rp',
    flag: 'IDR',
  ),
  Currency(
    name: 'Hungary Forint',
    code: 'HUF',
    pluralName: 'Hungarian forints',
    symbol: 'Ft',
    flag: 'HUF',
  ),
  Currency(
    name: 'Czech Koruna',
    code: 'CZK',
    pluralName: 'Czech Republic korunas',
    symbol: 'Kč',
    flag: 'CZK',
  ),
  Currency(
    name: 'Israel Shekel',
    code: 'ILS',
    pluralName: 'Israeli new sheqels',
    symbol: '₪',
    flag: 'ILS',
  ),
  Currency(
    name: 'Chile Peso',
    code: 'CLP',
    pluralName: 'Chilean pesos',
    symbol: '\$',
    flag: 'CLP',
  ),
  Currency(
    name: 'Philippines Peso',
    code: 'PHP',
    pluralName: 'Philippine pesos',
    symbol: '₱',
    flag: 'PHP',
  ),
  Currency(
    name: 'Emirati Dirham',
    code: 'AED',
    pluralName: 'UAE dirhams',
    symbol: 'د.إ',
    flag: 'AED',
  ),
  Currency(
    name: 'Colombia Peso',
    code: 'COP',
    pluralName: 'Colombian pesos',
    symbol: '\$',
    flag: 'COP',
  ),
  Currency(
    name: 'Saudi Arabia Riyal',
    code: 'SAR',
    pluralName: 'Saudi riyals',
    symbol: '﷼',
    flag: 'SAR',
  ),
  Currency(
    name: 'Malaysia Ringgit',
    code: 'MYR',
    pluralName: 'Malaysian ringgits',
    symbol: 'RM',
    flag: 'MYR',
  ),
  Currency(
    name: 'Romania Leu',
    code: 'RON',
    pluralName: 'Romanian lei',
    symbol: 'L',
    flag: 'RON',
  ),
  Currency(
    name: 'Afghanistan Afghani',
    code: 'AFN',
    pluralName: 'Afghan Afghanis',
    symbol: '؋',
    flag: 'AFN',
  ),
  Currency(
    name: 'Argentine Peso',
    code: 'ARS',
    pluralName: 'Argentine pesos',
    symbol: '\$',
    flag: 'ARS',
  ),
  Currency(
    name: 'Barbados Dollar',
    code: 'BBD',
    pluralName: 'Zimbabwean dollars',
    symbol: '\$',
    flag: 'BBD',
  ),
  Currency(
    name: 'Bangladeshi Taka',
    code: 'BDT',
    pluralName: 'Bangladeshi takas',
    symbol: ' Tk',
    flag: 'BDT',
  ),
  Currency(
    name: 'Bulgarian Lev',
    code: 'BGN',
    pluralName: 'Bulgarian leva',
    symbol: 'лв',
    flag: 'BGN',
  ),
  Currency(
    name: 'Bahraini Dinar',
    code: 'BHD',
    pluralName: 'Bahraini dinars',
    symbol: 'BD',
    flag: 'BHD',
  ),
  Currency(
    name: 'Bermuda Dollar',
    code: 'BMD',
    pluralName: 'Bermuda dollars',
    symbol: '\$',
    flag: 'BMD',
  ),
  Currency(
    name: 'Brunei Darussalam Dollar',
    code: 'BND',
    pluralName: 'Brunei dollars',
    symbol: '\$',
    flag: 'BND',
  ),
  Currency(
    name: 'Bolivia Bolíviano',
    code: 'BOB',
    pluralName: 'Bolivian bolivianos',
    symbol: '\$b',
    flag: 'BOB',
  ),
  Currency(
    name: 'Bhutanese Ngultrum',
    code: 'BTN',
    pluralName: 'Bhutanese ngultrums',
    symbol: 'Nu.',
    flag: 'BTN',
  ),
  Currency(
    name: 'Belize Dollar',
    code: 'BZD',
    pluralName: 'Belize dollars',
    symbol: 'BZ\$',
    flag: 'BZD',
  ),
  Currency(
    name: 'Costa Rica Colon',
    code: 'CRC',
    pluralName: 'Costa Rican colóns',
    symbol: '₡',
    flag: 'CRC',
  ),
  Currency(
    name: 'Dominican Republic Peso',
    code: 'DOP',
    pluralName: 'Dominican pesos',
    symbol: 'RD\$',
    flag: 'DOP',
  ),
  Currency(
    name: 'Egypt Pound',
    code: 'EGP',
    pluralName: 'Egyptian pounds',
    symbol: '£',
    flag: 'EGP',
  ),
  Currency(
    name: 'Ethiopian Birr',
    code: 'ETB',
    pluralName: 'Ethiopian birrs',
    symbol: 'Br',
    flag: 'ETB',
  ),
  Currency(
    name: 'Georgian Lari',
    code: 'GEL',
    pluralName: 'Georgian laris',
    symbol: '₾',
    flag: 'GEL',
  ),
  Currency(
    name: 'Ghana Cedi',
    code: 'GHS',
    pluralName: 'Ghanaian cedis',
    symbol: '₵',
    flag: 'GHS',
  ),
  Currency(
    name: 'Gambian dalasi',
    code: 'GMD',
    pluralName: 'Gambian dalasis',
    symbol: 'D',
    flag: 'GMD',
  ),
  Currency(
    name: 'Guyana Dollar',
    code: 'GYD',
    pluralName: 'Guyana dollars',
    symbol: '\$',
    flag: 'GYD',
  ),
  Currency(
    name: 'Croatia Kuna',
    code: 'HRK',
    pluralName: 'Croatian kunas',
    symbol: 'kn',
    flag: 'HRK',
  ),
  Currency(
    name: 'Iceland Krona',
    code: 'ISK',
    pluralName: 'Icelandic krónur',
    symbol: 'kr',
    flag: 'ISK',
  ),
  Currency(
    name: 'Jamaica Dollar',
    code: 'JMD',
    pluralName: 'Jamaican dollars',
    symbol: 'J\$',
    flag: 'JMD',
  ),
  Currency(
    name: 'Kenyan Shilling',
    code: 'KES',
    pluralName: 'Kenyan shillings',
    symbol: 'KSh',
    flag: 'KES',
  ),
  Currency(
    name: 'Kuwaiti Dinar',
    code: 'KWD',
    pluralName: 'Kuwaiti dinars',
    symbol: 'د.ك',
    flag: 'KWD',
  ),
  Currency(
    name: 'Cayman Islands Dollar',
    code: 'KYD',
    pluralName: 'Cayman islands dollars',
    symbol: '\$',
    flag: 'KYD',
  ),
  Currency(
    name: 'Kazakhstan Tenge',
    code: 'KZT',
    pluralName: 'Kazakhstani tenges',
    symbol: '〒',
    flag: 'KZT',
  ),
  Currency(
    name: 'Laos Kip',
    code: 'LAK',
    pluralName: 'Laos Kip',
    symbol: '₭',
    flag: 'LAK',
  ),
  Currency(
    name: 'Sri Lanka Rupee',
    code: 'LKR',
    pluralName: 'Sri Lankan rupees',
    symbol: '₨',
    flag: 'LKR',
  ),
  Currency(
    name: 'Liberia Dollar',
    code: 'LRD',
    pluralName: 'Liberia dollars',
    symbol: '\$',
    flag: 'LRD',
  ),
  Currency(
    name: 'Moroccan Dirham',
    code: 'MAD',
    pluralName: 'Moroccan dirhams',
    symbol: 'MAD',
    flag: 'MAD',
  ),
  Currency(
    name: 'Moldovan Leu',
    code: 'MDL',
    pluralName: 'Moldovan lei',
    symbol: 'L',
    flag: 'MDL',
  ),
  Currency(
    name: 'Macedonia Denar',
    code: 'MKD',
    pluralName: 'Macedonian denari',
    symbol: 'ден',
    flag: 'MKD',
  ),
  Currency(
    name: 'Mongolia Tughrik',
    code: 'MNT',
    pluralName: 'Mongolia tugriks',
    symbol: '₮',
    flag: 'MNT',
  ),
  Currency(
    name: 'Mauritius Rupee',
    code: 'MUR',
    pluralName: 'Mauritian rupees',
    symbol: '₨',
    flag: 'MUR',
  ),
  Currency(
    name: 'Malawian Kwacha',
    code: 'MWK',
    pluralName: 'Malawian kwachas',
    symbol: 'MK',
    flag: 'MWK',
  ),
  Currency(
    name: 'Mozambique Metical',
    code: 'MZN',
    pluralName: 'Mozambican meticals',
    symbol: 'MT',
    flag: 'MZN',
  ),
  Currency(
    name: 'Namibia Dollar',
    code: 'NAD',
    pluralName: 'Namibian dollars',
    symbol: '\$',
    flag: 'NAD',
  ),
  Currency(
    name: 'Nigeria Naira',
    code: 'NGN',
    pluralName: 'Nigerian nairas',
    symbol: '₦',
    flag: 'NGN',
  ),
  Currency(
    name: 'Nicaragua Cordoba',
    code: 'NIO',
    pluralName: 'Nicaraguan córdobas',
    symbol: 'C\$',
    flag: 'NIO',
  ),
  Currency(
    name: 'Oman Rial',
    code: 'OMR',
    pluralName: 'Omani rials',
    symbol: '﷼',
    flag: 'OMR',
  ),
  Currency(
    name: 'Peru Sol',
    code: 'PEN',
    pluralName: 'Peruvian nuevos soles',
    symbol: 'S/.',
    flag: 'PEN',
  ),
  Currency(
    name: 'Papua New Guinean Kina',
    code: 'PGK',
    pluralName: 'Papua New Guinean Kina',
    symbol: 'K',
    flag: 'PGK',
  ),
  Currency(
    name: 'Pakistan Rupee',
    code: 'PKR',
    pluralName: 'Pakistani rupees',
    symbol: '₨',
    flag: 'PKR',
  ),
  Currency(
    name: 'Paraguay Guarani',
    code: 'PYG',
    pluralName: 'Paraguayan guaranis',
    symbol: '₲',
    flag: 'PYG',
  ),
  Currency(
    name: 'Qatar Riyal',
    code: 'QAR',
    pluralName: 'Qatari rials',
    symbol: '﷼',
    flag: 'QAR',
  ),
  Currency(
    name: 'Serbia Dinar',
    code: 'RSD',
    pluralName: 'Serbian dinars',
    symbol: 'Дин.',
    flag: 'RSD',
  ),
  Currency(
    name: 'Somalia Shilling',
    code: 'SOS',
    pluralName: 'Somali shillings',
    symbol: 'S',
    flag: 'SOS',
  ),
  Currency(
    name: 'Suriname Dollar',
    code: 'SRD',
    pluralName: 'Suriname Dollars',
    symbol: '\$',
    flag: 'SRD',
  ),
  Currency(
    name: 'Trinidad and Tobago Dollar',
    code: 'TTD',
    pluralName: 'Trinidad and Tobago dollars',
    symbol: 'TT\$',
    flag: 'TTD',
  ),
  Currency(
    name: 'Tanzanian Shilling',
    code: 'TZS',
    pluralName: 'Tanzanian shillings',
    symbol: 'TSh',
    flag: 'TZS',
  ),
  Currency(
    name: 'Ukraine Hryvnia',
    code: 'UAH',
    pluralName: 'Ukrainian hryvnias',
    symbol: '₴',
    flag: 'UAH',
  ),
  Currency(
    name: 'Ugandan Shilling',
    code: 'UGX',
    pluralName: 'Ugandan shillings',
    symbol: 'USh',
    flag: 'UGX',
  ),
  Currency(
    name: 'Uruguay Peso',
    code: 'UYU',
    pluralName: 'Uruguayan pesos',
    symbol: '\$U',
    flag: 'UYU',
  ),
  Currency(
    name: 'Venezuela Bolívar',
    code: 'VEF',
    pluralName: 'Venezuelan bolívars',
    symbol: 'Bs',
    flag: 'VEF',
  ),
  Currency(
    name: 'Viet Nam Dong',
    code: 'VND',
    pluralName: 'Vietnamese dong',
    symbol: '₫',
    flag: 'VND',
  ),
  Currency(
    name: 'Yemen Rial',
    code: 'YER',
    pluralName: 'Yemeni rials',
    symbol: '﷼',
    flag: 'YER',
  ),
  Currency(
    name: 'Albanian Lek',
    code: 'ALL',
    pluralName: 'Albanian lekë',
    symbol: 'Lek',
    flag: 'ALB',
  ),
  Currency(
    name: 'Armenian Dram',
    code: 'AMD',
    pluralName: 'Armenian drams',
    symbol: '֏',
    flag: 'AM',
  ),
  Currency(
    name: 'Azerbaijani Manat',
    code: 'AZN',
    pluralName: 'Azerbaijani manats',
    symbol: '₼',
    flag: 'AZE',
  ),
  Currency(
    name: 'Burundian Franc',
    code: 'BI',
    pluralName: 'Burundian Franc',
    symbol: 'FBu',
    flag: 'BI',
  ),
  Currency(
    name: 'Botswanan Pula',
    code: 'BWP',
    pluralName: 'Botswanan pulas',
    symbol: 'P',
    flag: 'BW',
  ),
  Currency(
    name: 'Belarussian Ruble',
    code: 'BYN',
    pluralName: 'Belarusian rubles',
    symbol: 'Br',
    flag: 'BY',
  ),
];
